package com.google.sps;

import com.google.cloud.datastore.Datastore;
import com.google.cloud.datastore.DatastoreOptions;
import com.google.cloud.datastore.Entity;
import com.google.cloud.datastore.FullEntity;
import com.google.cloud.datastore.Key;
import com.google.cloud.datastore.KeyFactory;

/** Puzzle DAO implementation*/
public class PuzzleDao implements Dao<Puzzle> {

    private Datastore datastore;
    private KeyFactory keyFactory;

    public PuzzleDao() {
      datastore = DatastoreOptions.getDefaultInstance().getService();
      keyFactory = datastore.newKeyFactory().setKind("Puzzle");
    }

    @Override
    public Puzzle create(Puzzle puzzle) {
      //saves puzzle object on datastore
      FullEntity taskEntity =
        Entity.newBuilder(keyFactory.newKey())
          .set("imageUrl", puzzle.getImageUrl())
          .build();
      Entity entity = datastore.put(taskEntity);

      //saves the id generated by datastore on the puzzle object
      puzzle.setPuzzleId(entity.getKey().getId().toString());

      return puzzle;
    }

    @Override
    public void update(Puzzle puzzle) {
      //updates the entity with the data contained in "puzzle", 
      // except the id which is used to search for the entity.
      Entity task = 
        Entity.newBuilder(datastore.get(generateKey(puzzle.getPuzzleId())))
          .set("imageUrl", puzzle.getImageUrl())
          .build();
      datastore.update(task);
    }

    @Override
    public Puzzle read(String puzzleId) {
      //reads the entity whose id match "puzzleID"
      Entity entity = datastore.get(generateKey(puzzleId));
      
      //saves the retrieved data into a "Puzzle" object
      Puzzle puzzle = new Puzzle()
        .setPuzzleId(entity.getKey().getId().toString())
        .setImageUrl(entity.getString("imageUrl"));

      //returns the object
      return puzzle;
    }

    @Override
    public void delete(String puzzleId) {
      //deletes the entity whose id match "puzzleID"
      datastore.delete(generateKey(puzzleId));
    }

    private Key generateKey(String puzzleId) {
      return keyFactory.newKey(Long.parseLong(puzzleId));
    }
}